### ISSUE TITLE
Failed to install superviseur

### ISSUE THREAD

**Issue by judicaelandria** [tsirysndr/superviseur#12]
Running the command
`cargo install --path .` is always failing. I don't see any error from cargo itself, so I suspect it's coming from the project
<img width="841" alt="Screenshot 2023-03-12 at 11 24 47 AM" src="https://user-images.githubusercontent.com/46365844/224533286-af3f29e8-47a7-42bd-8c49-343e6b4631e0.png">

**Comment by tsirysndr** [comment]
The compilation depends on the `protoc` compiler, I just updated the README on the installation

**Comment by judicaelandria** [comment]
I did install `photobuf`
I'll try to upgrade cargo first and photobuf if it will solve the issue
